name: Continuous Integration

on: 
    - pull_request
    - push

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        
        - name: Setup TeX Live
          uses: teatimeguest/setup-texlive-action@v3
          with:
            package-file:  |
              ci/texlive/texlive_packages
        - name: Sphinx Action
          uses: ammaraskar/sphinx-action@master
          with:
            docs-folder: "."